### PR TITLE
Added full support for "Drive Droid" and "USB Keyboard" apps

### PR DESCRIPTION
**Pull request by I02RUBERDUCKS**
These two commits add full support for both of these two apps, allowing allowing drive droid to act as both a USB drive and a CD-ROM, and allowing USB Keyboard to allow the phone to emulate a keyboard and mouse over USB.

Thanks,
Daniel Thorpe/x10man on XDA

### CODE REVIEW

**Comment by DespairFactor** [comment]
Just wondering what the origin of these commits are, or did you actually make them yourself?

**Comment by I02RUBERDUCKS** [comment]
Probably should have mentioned that, apologies. Drive Droid patch comes from https://github.com/CyanogenMod/android_kernel_lge_hammerhead/commit/46bd47757a9f34c1d95dd2620414893212fb0526?diff=unified - linked from the Drive Droid thread under as how to add support yourself, and the USB Keyboard patch from https://github.com/pelya/android-keyboard-gadget/blob/master/kernel-3.4.patch - once again linked as to add support yourself from the Play Store page. I have tested these on my nexus 5, the kernel builds successfully and the functionality is present after flashing.

**Comment by DespairFactor** [comment]
Could you resubmit the first commit with the proper authorship? the second is fine as it is a patch being applied.

**Comment by I02RUBERDUCKS** [comment]
Sure, apologies for sounding stupid but how would one go about doing that? I'm new to git, so I'm not sure how to perform such an action

**Comment by DespairFactor** [comment]
Are these on your github? I will do it manually by picking them from you. If you need assistance in the future reach me via hangouts, I will remove these comments so people can't find them:)

**Comment by I02RUBERDUCKS** [comment]
These are on github. Thanks :) I believe I have done it, is the latest commit correct in terms of authorship?

**Comment by DespairFactor** [comment]
Yes it is correct now, I will merge:) TY

**Pull request merged**
